### ISSUE TITLE
How to delete  data from the main table as well as in the junction table?

### ISSUE THREAD

**Issue by neerajs046** [arogachev/yii2-many-to-many#13]
Hello @arogachev  your extension really help me a lot. But when I am deleting the user it gives me Integrity constraint violation. How to fix this issue.

**Comment by arogachev** [comment]
To delete data, you just need to modify editable attribute value.

For example, if this was initial value:

``` php
$model = new Test;
$model->getManyToManyRelation('users')->fill();
var_dump($model->editableUsers) // [1, 2]
```

to delete user with `id = 2`, you just remove it from array:

``` php
$model->editableUsers = [1];
$model->save();
```

As for integrity constraint violation error, please provide your code and according database tables structure.

**Comment by arogachev** [comment]
No further feedback, closing this.
