### ISSUE TITLE
fillingRoute setup

### ISSUE THREAD

**Issue by drsdre** [arogachev/yii2-many-to-many#5]
Hi,

Thanks for the plugin. Great work!

I'm wondering how the fillingRoute is supposed to work. Should it return items in a certain format (array, json, etc.?).

Currently I'm able to to write the selection to disk, but the selection is not pre-selected on the next form visit. Is this related to the fillingRoute or is there something else I missed?

Andre

**Comment by arogachev** [comment]
Hi!

Yes, it's related with `fillingRoute` option.

First of all, the main information is available in one of examples in README (in comments):

``` php
'fillingRoute' => 'tests/default/update', // Full route name (including module id if it's inside module) for auto filling editable attribute with existing data. You can also pass array of routes.
```

Also I explained it in #2.

Is it more clear now?
