### ISSUE TITLE
Relations get deleted when current route is not in filling route array

### ISSUE THREAD

**Issue by akorinek** [arogachev/yii2-many-to-many#9]
The fillingroute array is problematic, since it makes the Behavior delete all relations if the model is updated but the editable attribute has not been filled because the current route was accidentally left out of the filling route array.

Maybe the update action should not run, when the current route is not in the filling route array. Otherwise there is the constant thread that the relations get lost.

**Comment by arogachev** [comment]
Yes, you are right. Will think about how to handle that.

**Comment by karakum** [comment]
I have the same problem. It was very unexpectedly for me

**Comment by arogachev** [comment]
@karakum I am planning to get rid of `fillingRoute` option completely in new release, not only because of that problem:
- model is not appropriate place for handling routes;
- usage in console environment.

But user should add something like `$model->fillManyToManyRelations()` in proper place (right after initialization). Is it OK, how do you think?

Initially I thought it will be better to handle all in one config, but it turns out a problem, specifically with `fillingRoute` property.

**Comment by karakum** [comment]
@arogachev, i think it's OK if updating(deleting) relations will be only if I call `$model->fillManyToManyRelations()`

**Comment by arogachev** [comment]
@karakum OK. I will add fix and new release soon.

**Comment by karakum** [comment]
Can I ask for one more enhancement?
In my junction table has sort column and filling relations according to it possible only using joining. Now filling perform by two query

> SELECT \* FROM `order_item` WHERE `order_id` = 100
> SELECT \* FROM `item` WHERE `item_id` IN (...)

Additional data in junction table also possible and ability getting it would be very good ;)

**Comment by akorinek** [comment]
Maybe there should be an autofill flag in the behavior? In my case filling the relation list is cheap and I would want to always have it filled for the comfort of not needing to think about when to manually fill it.

**Comment by arogachev** [comment]
@karakum Yes, of course. But I don't fully understand your second problem. Please create separate issue for that and describe with more details. You can use russian if you want.

@akorinek Good idea. :+1: I was thinking about it. I'll add this as well.

**Comment by karakum** [comment]
@arogachev, How can I make my model to fill relation before calling `$model->save()` method till you new release?

**Comment by arogachev** [comment]
@karakum I already implemented it, but not pushed yet. Is it acceptable to you to wait till tomorrow?

**Comment by arogachev** [comment]
Please wait a bit, it will be added tomorrow. Need to add tests and update docs.

**Comment by arogachev** [comment]
It's hard to do now because current implementation depends on `fillingRoute`.

**Comment by karakum** [comment]
удаление связей вне `actionUpdate()` это серьезный баг. 
Не думаю, что стоит задумываться, как сохранить его, обеспечивая обратную совместимость с пред. версиями. 
Как минимум нужно заполнять связи ВСЕГДА, кому это не требуется - дать возможность отключить(параметры behavior + программным способом). Такое решение, думаю, устроит и тех, кто пока не догадывается об этом баге.
Жду с нетерпением релиз, а пока пришлось перед сохранением вызывать

>    public function disableManyToMany()
>    {
>        $this->noMTM = true;
>        $this->detachBehavior('manyToMany');
>    }

**Comment by arogachev** [comment]
@karakum Это не баг, так как это было описано в документации. То есть если программист указал неверный route или забыл его сменить в конфиге после смены URL, то это все-таки его ошибка. Однако действительно, такая привязка показала себя плохо. Сделано, смотрите README.

@akorinek Done. Check updated README.

**Comment by karakum** [comment]
@arogachev ну как же это не баг? 

> public function update()
> {
>    $this->delete();
>    $this->insert();
> }
> ...
> public function fill()
> {
>    if (!$this->fillingRoute || !Yii::$app->controller) {
>        return;
>    }
> 
>    if (in_array(Yii::$app->controller->route, $this->fillingRoute)) {
>        $this->setEditableList($this->getRelatedList());
>    }
> }

`ManyToManyRelation::update()` вызывается ВСЕГДА после обновления модели, а `ManyToManyRelation::fill()` - только в определенном маршруте. 
В документации было сказано "Auto filling of editable attribute for given route(s)".
Полагаю БАГ заключается именно в том, что обновление/удаление связей выполняется ВСЕГДА при сохранении существующей модели, в то время, как сами связи считываются только по  маршруту `fillingRoute`.
Из "Auto filling of editable attribute for given route(s)", думаю, никто не ожидает что вне "given route(s)" связи будут удаляться при обычном сохранении модели.
Извиняюсь, за занудство и оффтоп.
Спасибо за релиз!

**Comment by karakum** [comment]
Предлагаю аналогичным образом добавить опцию `autoUpdate` и учитывать ее в `ManyToManyRelation::update()`. 

Признаюсь, в моем конкретном случае, искусственный атрибут, заполняемый механизмом `autoFill` **абсолютно бесполезен и никогда не используется**, кроме основного механизма редактирования(множественный селект). От плагина требуется только обновить связи в промежуточной таблице.

Т.е. в моем случае `autoFill=false` и `$model->getManyToManyRelation('users')->fill();` в `actionUpdate()` - самый оптимальный вариант.

НО! при сохранении опять связи потеряются, если я или кто-то другой(даже не подозревающий об этом) забудет выполнить `$model->getManyToManyRelation('users')->fill();` перед сохранением!

В то же время, решение текущей проблемы через `autoFill=true`(что сейчас по-умолчанию) создаст бесполезную нагрузку на бд при каждой загрузке экземпляра моей модели.

Полагаю, что опция `autoUpdate` позволит более гибко настраивать поведение. Пусть она будет по-умолчанию `true`, как сейчас и есть.

_хотя, если честно, то в релизе я ожидал, что `autoFill` будет учитываться в методе `update()` :(. Ведь если мы намеренно не загрузили связи, то зачем их при этом удалять?_

**Comment by arogachev** [comment]
@karakum Признаю, действительно, это баг. Фикс будет в ближайшее время. В опции `autoUpdate` нет необходимости, достаточно просто ориентироваться на заполненность.

**Comment by arogachev** [comment]
@karakum Обновитесь, в версии 0.2.1 данная проблема устранена. Спасибо.

@akorinek Please update to 0.2.1 version.
